config/routes.rb
Rails.application.routes.draw do

  resources :vendors
  resources :v_types
  resources :search

  root 'search#index'

end

app/models/v_type.rb
class VType < ActiveRecord::Base
  has_and_belongs_to_many :vendors
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_and_belongs_to_many :v_types
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end
end

app/controllers/v_types_controller.rb
class VTypesController < ApplicationController
  def index
    @vtypes = VType.all
  end

  def new
    @vtype = VType.new
  end

  def create
    @vtype = VType.new(vtype_params)
    if @vtype.save
      redirect_to @vtype
    else
      render 'new'
    end
  end

  def show
    @vtype = find_vtype_by_id
  end

  def edit
    @vtype = find_vtype_by_id
  end

  def update
    @vtype = find_vtype_by_id
    if @vtype.update_attributes(vtype_params)
      redirect_to @vtype
    else
      render 'edit'
    end
  end

  def destroy
    find_vtype_by_id.destroy
    redirect_to v_types_url
  end

  private
    def vtype_params
      params.require(:v_type).permit(:name)
    end

    def find_vtype_by_id
      VType.find(params[:id])
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def index
    @vendors = Vendor.all
  end

  def new
    @vendor = Vendor.new
    @vtypes = VType.all.map { |vtype| [vtype.name, vtype.id] }
  end

  def create
    @vendor = Vendor.new(vendor_params)
    if @vendor.save
      redirect_to @vendor
    else
      render 'new'
    end
  end

  def show
    @vendor = Vendor.find(params[:id])
  end

  def edit
    @vendor = Vendor.find(params[:id])
    @vtypes = VType.all
  end

  def update
    @vendor = Vendor.find(params[:id])
    @vendor.v_types.delete_all
    if @vendor.update_attributes(vendor_params)
      params[:vendor][:v_types].each do |k,v|
        if !k.empty?
          @vendor.v_types << VType.find(k)
        end
      end
      redirect_to @vendor
    else
      render 'edit'
    end
  end

  def destroy
    Vendor.find(params[:id]).destroy
    redirect_to vendors_url
  end

  private

    def vendor_params
      params.require(:vendor).permit(:name, :url, :logo, :v_types)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Prackit", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Vendors", vendors_path %></li>
        <li><%= link_to "Vendor Types", v_types_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prackit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/search/index.html.erb
<h2>Enter URL to track on Prackit</h2>
<hr />

<%= form_tag("/search", method: "get") do %>
  <%= label :q, "URL:" %>
  <%= text_field :q, :q, class: "form-control" %>
  <%= submit_tag "Track", class: "btn btn-primary" %>
<% end %>

app/views/v_types/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @vtype do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, :placeholder => "Type the vendor type name here", class: "form-control" %>

      <%= f.submit "Update Vendor Type", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/v_types/index.html.erb
<h2>Vendor Types | <%= link_to "New Vendor Type", new_v_type_path %></h2>

<hr />

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
<% @vtypes.each do |vtype| %>
  <tr>
    <td><%= link_to vtype.name, vtype %></td>
    <td><%= link_to "edit", edit_v_type_path(vtype) %>
    <td><%= link_to "delete", vtype, method: :delete,
                                      data: { confirm: "You sure?" } %>
  </tr>
<% end %>
</table>

app/views/v_types/new.html.erb
<h2>Add New Vendor Type</h2>

<hr />

<%= form_for @vtype do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :placeholder => "Type the vendor type here", class: "form-control" %>

  <%= f.submit "Add Vendor Type", class: "btn btn-primary" %>
<% end %>

app/views/v_types/show.html.erb
<h2><%= @vtype.name %> | <%= link_to 'Edit', edit_vendor_path(@vtype) %></h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Vendors</th>
    </tr>
  </thead>
  <tr>
    <td><%= @vtype.name %></td>
    <% if @vtype.vendors.count > 0 %>
    <td>
      <% @vtype.vendors.each do |vendor| %>
      <%= vendor.name %><br />
      <% end %>
    </td>
    <% elsif %>
    <td>No vendors with type</td>
    <% end %>
  </tr>
</table>

app/views/vendors/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @vendor do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, :placeholder => "Type the vendor name here", class: 'form-control' %>

      <%= f.label :url %>
      <%= f.text_field :url, :placeholder => "Type the URL here", class: 'form-control' %>

      <%= f.label :logo %>
      <%= f.text_field :logo, :placeholder => "Enter URL for logo here", class: 'form-control' %>

      <%= f.label :v_types, "Vendor Types" %>
      <%= f.select(:v_types, options_from_collection_for_select(@vtypes, :id, :name, @vendor.v_types.map {|j| j.id}), {}, {:multiple => true}) %>

      <%= f.submit "Update Vendor", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/vendors/index.html.erb
<h2>Prackit Certified Vendors | <%= link_to "Add New", new_vendor_path %></h2>

<hr />

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>URL</th>
      <th>Logo</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
<% @vendors.each do |vendor| %>
  <tr>
    <td><%= link_to vendor.name, vendor %></td>
    <td><%= vendor.url %></td>
    <td><%= image_tag(vendor.logo, width: "200") %></td>
    <td><%= link_to "edit", edit_vendor_path(vendor) %>
    <td><%= link_to "delete", vendor, method: :delete,
                                      data: { confirm: "You sure?" } %>
  </tr>
<% end %>
</table>

app/views/vendors/new.html.erb
<h2>Add New Vendor</h2>

<hr />

<%= form_for @vendor do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :placeholder => "Type the vendor name here", class: "form-control" %>

  <%= f.label :url %>
  <%= f.text_field :url, :placeholder => "Type the URL here", class: "form-control" %>

  <%= f.label :logo %>
  <%= f.text_field :logo, :placeholder => "Enter URL for logo here", class: "form-control" %>

  <%= f.submit "Add Vendor", class: "btn btn-primary" %>
<% end %>

app/views/vendors/show.html.erb
<h2><%= @vendor.name %> | <%= link_to 'Edit', edit_vendor_path(@vendor) %></h2>
<table>
  <thead>
    <tr>
      <th>URL</th>
      <th>Logo</th>
      <th>Vendor Types</th>
    </tr>
  </thead>
  <tr>
    <td><%= @vendor.url %></td>
    <td><%= image_tag(@vendor.logo, width: "200") %></td>
    <% if @vendor.v_types.count > 0 %>
    <td>
      <% @vendor.v_types.each do |v| %>
      <%= v.name %><br />
      <% end %>
    </td>
    <% else %>
    <td>Vendor not associated with any types</td>
    <% end %>
  </tr>
</table>